### PR TITLE
Update grep.go

### PR DESCRIPTION
**Pull request by Sy3Omda**
necessary changes to slack hook, add another secrets regex

### CODE REVIEW

**Comment by hahwul** [comment]
@Sy3Omda 
Hi :D 
Thank your for submit pull request!

There was a `pkg/scanning/grep.go:30:43:unknown escape` bug in the slack hook pattern, so I fixed it.
And.. I have a one question, why did you change the number of digits below to 10 in the slack hook pattern? Slack hook url is usually matched at 8.

Origin
```
"dalfox-slack-webhook": "https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}",
```

Your PR
```
"dalfox-slack-webhook": "https:\/\/hooks.slack.com\/services\/T[a-zA-Z0-9_]{10}\/B[a-zA-Z0-9_]{10}\/[a-zA-Z0-9_]{24}",
```

I remember it as eight digits, but if there are ten digits case, I think it would be better to add one more to the regular expression or modified regular expression.

**Comment by Sy3Omda** [comment]
Hi @hahwul ,
those tested on my currently bot which is working right now.
plus the channel regex was changed too, would you like me to update it too or you will do ?
I'll appreciate u time  if you created a bot & channel in slack and try it yourself to confirm it

**Comment by hahwul** [comment]
Hello again @Sy3Omda 
A similar example is the same pattern for the slide hook url of scan template in nuclei-templates. When I tested with my hook url, I got 8 correct. (The example in the [official documentation](https://api.slack.com/messaging/webhooks#) is the same too.)

https://github.com/projectdiscovery/nuclei-templates/blob/b43c97360e81c0f29f57f42b6131cc071d810f42/exposures/tokens/slack/slack-webhook-token.yaml

```yml
requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        part: body
        regex:
          - "https://hooks\\.slack\\.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}"
```

Did you mean bot or usertoken as below?

https://github.com/projectdiscovery/nuclei-templates/blob/b43c97360e81c0f29f57f42b6131cc071d810f42/exposures/tokens/slack/slack-bot-token.yaml

https://github.com/projectdiscovery/nuclei-templates/blob/b43c97360e81c0f29f57f42b6131cc071d810f42/exposures/tokens/slack/slack-user-token.yaml

**Comment by hahwul** [comment]
@Sy3Omda 
Let me know if there is a case that is detected by 10. Maybe I didn't see notice, but if it's changed to 10, I think it's right to detect it with two rules. (A lot of users will still be 8)

**Comment by Sy3Omda** [comment]
Hi @hahwul ,

sorry for being busy :)
BTW you could filter two regex in one rule to match yours and any other hook like mine
```
https:\/\/hooks.slack.com\/services\/T[a-zA-Z0-9_]{8,10}\/B[a-zA-Z0-9_]{8,10}\/[a-zA-Z0-9_]{24}
```

which is based on regex101

the second thing i need to inquire about i noticed that u dose not escape forward slash `/` which is strange for me !!
do u  grep it without escaping ?

**Comment by hahwul** [comment]
Hello again @Sy3Omda 
I've just merged with the current code. and I'll add 10 cases received from you! 

The slash issue is a bit unique, but I think Golang handles it like that. Of course, it is used as `\/` based on regex101, but it seems to be handled directly as `/` in the code. 

Is the build successful with the `\/` pattern?
(ref: https://github.com/hahwul/dalfox/pull/264/checks?sha=422f1c302b38a739841421dacc4dda05a678cb10)

**Comment by hahwul** [comment]
Maybe the regular expression should be stored as string in golang, so it cannot be used as `\/`. If you want to mark `\/`, need to mark `\\/`. 

```go
var pattern = regexp.MustCompile(regex)
```

However, dalfox-slack-webhook pattern used as `/` because `/` is being detected well during the test.

**Comment by Sy3Omda** [comment]
It's okay as long as golang handle it very well.
Just modify the regex itself to ```{8,10}```
to detect both hooks

**Pull request merged**
