### PR TITLE
Add --cookie-from-raw option

### PR DESCRIPTION
**Pull request by KodjoB**
Hi, 

I added an option to load cookies from a raw http request file, like the one we get from BurpSuite.

### CODE REVIEW

**Comment by hahwul** [comment]
Hi @KodjoB 
First of all, thank you so much for the PR! I have a question about the concept. 

Is the reason for adding features is that only cookie information should be read from the raw http file? Or is it to scan multiple URLs with cookies from raw requests?

Currently, there is a function to process raw http requests in the `dalfox file --rawdata`. 
so if you make an option to scanning multiple urls with cookies form file, I think we need to modify the option name. (e.g `--cookie-from-raw`)

```
Usage:
  dalfox file [filePath] [flags]

Flags:
  -h, --help        help for file
      --http        Using force http on rawdata mode
      --multicast   Scanning N*Host mode
      --rawdata     Using req rawdata from Burp/ZAP
```

**Comment by KodjoB** [comment]
Ok let me do that.

**Comment by KodjoB** [comment]
The concept is to scan multiple URLs with cookies from raw requests. To provide easy to use authenticated scan.

**Comment by hahwul** [comment]
Hello again @KodjoB 
Thank you so much for your comments and additional modifications! 
I 'll merge! Enjoy a nice rest of the day :D

**Comment by hahwul** [comment]
@KodjoB 
And It will be applied immediately in dev version, and the release will be released 2.3.0 within March.

**Comment by KodjoB** [comment]
What next feature can I work on ?

**Comment by leorac** [comment]
I think that is an issue with this functionality. Every time I try to run it with a burp request as input, it says that the first line is Malformed. It keeps saying for every first line of the file.

**Pull request merged**
