### PR TITLE
sql injection basic detection

### PR DESCRIPTION
**Pull request by bp0lr**
Hello!,
let me first thank you for this amazing tool.

Dalfox already has some rules to check some basic sql injecton, but mostly using errors coming from an xss attempt.
Following your code, I did some changes to have a custom payload list (a small one!) for sqli and test this list again each parameter.

These tests are run before the xss tests begging and are just a GET request for each parameter.

imagen

I hope you like it!

btw, I think that would be a good idea to have each payload list outside the code base and been loaded on run time.

pd: VS code just ran an autoformat on some files. 
Sorry about that!

### CODE REVIEW

**Comment by hahwul** [comment]
Hi @bp0lr 
Thank you so much for sending me your PR. It's suitable for directionality, and I've tested it and there's nothing special problem about it, so **I'll merge** 👍

And I'll make further modifications to the scanning order considering its concurrency

before
```go
	SqliAnalysis(target, options)

	var wait sync.WaitGroup
	task := 2
	wait.Add(task)
	go func() {
		defer wait.Done()
		printing.DalLog("SYSTEM", "Start static analysis.. 🔍", options)
		policy = StaticAnalysis(target, options)
	}()
	go func() {
		defer wait.Done()
		printing.DalLog("SYSTEM", "Start parameter analysis.. 🔍", options)
		params = ParameterAnalysis(target, options)
	}()
```
after (like it)
```go
	

	var wait sync.WaitGroup
	task := 3
	wait.Add(task)
	go func() {
		defer wait.Done()
		printing.DalLog("SYSTEM", "Start static analysis.. 🔍", options)
		policy = StaticAnalysis(target, options)
	}()
	go func() {
		defer wait.Done()
		printing.DalLog("SYSTEM", "Start parameter analysis.. 🔍", options)
		params = ParameterAnalysis(target, options)
	}()
        go func() {
                 defer wait.Done()
		printing.DalLog("SYSTEM", "Start SQLi analysis.. 🔍", options)
                 SqliAnalysis(target, options)
        }()
```

Have a nice day and hope you are safe from COVID19 🙏🏼

**Comment by hahwul** [comment]
@bp0lr 
Oh, and the latest (install from go-get) is immediately reflected, and the official release is scheduled for 2.2.0 in October, so it will be reflected at that time :D

**Comment by hahwul** [comment]
@bp0lr 
I integrated `SQLi` and `SSTI` under the name `BAV(Basic Another Vulnerability)` and changed it to follow the basic Concurrent policy to improve scan speed. If you have any additional comments, please let me know:D

default concurrency is 100, so 100 workers divide and process the work.
```go
//SqliAnalysis is basic check for SQL Injection
func SqliAnalysis(target string, options model.Options) {
	// sqli payload
	bpu, _ := url.Parse(target)
	bpd := bpu.Query()
	var wg sync.WaitGroup
	concurrency := options.Concurrence
	reqs := make(chan *http.Request)

	for i := 0; i < concurrency; i++ {
		wg.Add(1)
		go func(){
			for req := range reqs {
				SendReq(req, "toGrepping", options)
			}
			wg.Done()
		}()
	}

	for bpk := range bpd {
		for _, sqlipayload := range getSQLIPayload() {
			turl, _ := optimization.MakeRequestQuery(target, bpk, sqlipayload, "toGrepping", options)
			reqs <- turl
		}
	}
	close(reqs)
	wg.Wait()
}
```

```go
	go func() {
		defer wait.Done()
		printing.DalLog("SYSTEM", "Start BAV(Basic Another Vulnerability) analysis.. / like sqli,ssti  🔍", options)
		var bavWaitGroup sync.WaitGroup
		bavTask := 2
		bavWaitGroup.Add(bavTask)
		go func(){
			defer bavWaitGroup.Done()
			SqliAnalysis(target, options)
		}()
		go func(){
			defer bavWaitGroup.Done()
			SSTIAnalysis(target, options)
		}()
		bavWaitGroup.Wait()
		printing.DalLog("SYSTEM", "BAV analysis done ✓", options)
	}()
```

**Comment by bp0lr** [comment]
my only comment is that you are awesome!

**Comment by hahwul** [comment]
@bp0lr 
You are cooler. Thank you :D

**Pull request merged**
